name: Feature Request
description: Request a new feature or enhancement
title: "[Feature] <short description>"
labels: [feature]
body:
  - type: markdown
    attributes:
      value: |
        Describe the user outcome first, then implementation ideas.

        Need support for a `SPECIAL` or other custom vendor integration? Use this form.

        Telegram channel: https://t.me/tx_stock_monitor

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What pain point should be solved?
      placeholder: We cannot prioritize high-value restocks by region.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe preferred behavior and rough acceptance criteria.
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Expected Impact
      description: Accuracy, speed, maintenance cost, or user experience improvements.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Optional alternatives or constraints.
    validations:
      required: false
