name: Feature Request
description: Request a new feature or enhancement
title: "[Feature] <short description>"
labels: [feature]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What pain point does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe your preferred behavior.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Optional alternatives or constraints.
    validations:
      required: false
