name: Site Change Request
description: Add or edit a monitored site in config/sites.json
title: "[Site Change] <add|edit> <site-name>"
labels: [site-change]
body:
  - type: markdown
    attributes:
      value: |
        ## What This Form Does
        Use this form for **site add/edit** requests only.

        ## Automatic Validation
        - `expected_product_number` is required and must be a positive integer.
        - Automation will run a live product-count scan on the provided URL.
        - If scanned products are fewer than expected, the request is rejected automatically.

        ## SPECIAL / Custom Sites
        - `SPECIAL` and other custom integrations are **not** accepted here.
        - If you want support for a `SPECIAL` site, please open a **Feature Request** instead.

        ## Tips
        - Use the exact vendor portal URL (include protocol).
        - Use the scanner checkbox list below. Checked means enabled, unchecked means disabled.
        - Monitor updates: https://t.me/tx_stock_monitor

  - type: dropdown
    id: action
    attributes:
      label: Action
      description: What change should be applied?
      options:
        - add
        - edit
    validations:
      required: true

  - type: input
    id: site_name
    attributes:
      label: Site Name
      placeholder: ExampleHost
      description: Must match existing name when action is edit.
    validations:
      required: true

  - type: input
    id: base_url
    attributes:
      label: Base URL
      placeholder: https://example.com/
      description: Required for add/edit. Must start with http:// or https://
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Choose vendor panel type.
      options:
        - WHMCS
        - HostBill
    validations:
      required: true

  - type: input
    id: expected_product_number
    attributes:
      label: Expected Product Number
      placeholder: "20"
      description: Minimum product count expected from automated validation scan.
    validations:
      required: true

  - type: checkboxes
    id: scanner_options
    attributes:
      label: Scanner Options
      description: Check each scanner to enable it. Leave unchecked to disable it.
      options:
        - label: Enable discoverer
        - label: Enable product scanner
        - label: Enable category scanner

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Optional context, examples, or sample product URLs.
    validations:
      required: false
