name: Site Change Request
description: Add, edit, or delete a monitored site in config/sites.json
title: "[Site Change] <action> <site-name>"
labels: [site-change]
body:
  - type: markdown
    attributes:
      value: |
        Use this form for **site add/edit/delete** only.

        Validation rules for add/edit:
        - `expected_product_number` is required and must be a positive integer.
        - Automation will run a live product-count scan on the provided URL.
        - If scanned products are fewer than expected, the request is rejected automatically.

        Tips:
        - Use the exact vendor portal URL (include protocol).
        - For SPECIAL sites, set `special_crawler` (for example: `acck_api`, `akile_api`).
        - Monitor updates: https://t.me/tx_stock_monitor

  - type: dropdown
    id: action
    attributes:
      label: Action
      description: What change should be applied?
      options:
        - add
        - edit
        - delete
    validations:
      required: true

  - type: input
    id: site_name
    attributes:
      label: Site Name
      placeholder: ExampleHost
      description: Must match existing name when action is edit/delete.
    validations:
      required: true

  - type: input
    id: base_url
    attributes:
      label: Base URL
      placeholder: https://example.com/
      description: Required for add/edit. Must start with http:// or https://
    validations:
      required: false

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Choose vendor panel type.
      options:
        - WHMCS
        - HostBill
        - SPECIAL
    validations:
      required: true

  - type: input
    id: expected_product_number
    attributes:
      label: Expected Product Number
      placeholder: "20"
      description: Minimum product count expected from automated validation scan.
    validations:
      required: false

  - type: dropdown
    id: discoverer
    attributes:
      label: Enable discoverer
      options:
        - "true"
        - "false"
    validations:
      required: true

  - type: dropdown
    id: product_scanner
    attributes:
      label: Enable product scanner
      options:
        - "true"
        - "false"
    validations:
      required: true

  - type: dropdown
    id: category_scanner
    attributes:
      label: Enable category scanner
      options:
        - "true"
        - "false"
    validations:
      required: true

  - type: input
    id: special_crawler
    attributes:
      label: Special crawler
      placeholder: acck_api
      description: Required for SPECIAL platform; leave empty otherwise.
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Optional context, examples, or sample product URLs.
    validations:
      required: false
